### ISSUE TITLE
fatal error: 'private/qmetaobjectbuilder_p.h' on Mac

### ISSUE THREAD

**Issue by updega2** [commontk/PythonQt#65]
Hi,

I'm trying to build on macOS High Sierra, 10.13, and running into an issue with finding a Qt5Core header.

PythonQt.cpp:1951:10: fatal error: 'private/qmetaobjectbuilder_p.h' file not found

I've tried both Qt5.4.2 and Qt5.6 with branches patched-7 and patched-8 but none of them seem to work. 

There was a similar issue raised for windows previously: https://github.com/commontk/PythonQt/issues/62

The solution seems a little hacky. Are there plans to try and include the extra Qt5Core dir within cmake for PythonQt or will I need to do something similar?

Thanks!

**Comment by iltommi** [comment]
Hi,
In principle those headers are included with this line: https://github.com/commontk/PythonQt/blob/patched-8/CMakeLists.txt#L155

could you post the `cmake` line and the last output of `make VERBOSE=1` ?

**Comment by updega2** [comment]
Here is the cmake output:

-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
-- PythonQt: Required Qt components [Core;Widgets]
--         Qt5Core_PRIVATE_INCLUDE_DIRS: 
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework   
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adamupdegrove/Downloads/PythonQt/PythonQt-build

I added a print statement and it appears Qt5_Core_PRIVATE_INCLUDE_DIRS is empty.

Here is make VERBOSE=1 output:

[ 28%] Building CXX object CMakeFiles/PythonQt.dir/src/PythonQt.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DPYTHONQT_EXPORTS -DPYTHONQT_SUPPORT_NAME_PROPERTY -DPYTHONQT_USE_RELEASE_PYTHON_FALLBACK -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/usr/include/python2.7 -iframework /Users/adamupdegrove/qt-5.4.2/lib -isystem /Users/adamupdegrove/qt-5.4.2/lib/QtCore.framework/Headers -isystem /Users/adamupdegrove/qt-5.4.2/mkspecs/macx-clang -isystem /Users/adamupdegrove/qt-5.4.2/lib/QtWidgets.framework/Headers -isystem /Users/adamupdegrove/qt-5.4.2/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Headers -I/Users/adamupdegrove/Downloads/PythonQt/src  -fPIC   -fPIC -o CMakeFiles/PythonQt.dir/src/PythonQt.cpp.o -c /Users/adamupdegrove/Downloads/PythonQt/src/PythonQt.cpp
In file included from /Users/adamupdegrove/Downloads/PythonQt/src/PythonQt.cpp:48:
/Users/adamupdegrove/Downloads/PythonQt/src/PythonQtConversion.h:496:23: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
    PyObject* items = PyMapping_Items(val);
                      ^
/usr/include/python2.7/abstract.h:1354:50: note: expanded from macro 'PyMapping_Items'
#define PyMapping_Items(O) PyObject_CallMethod(O,"items",NULL)
                                                 ^
/Users/adamupdegrove/Downloads/PythonQt/src/PythonQt.cpp:1951:10: fatal error: 'private/qmetaobjectbuilder_p.h' file not found
#include <private/qmetaobjectbuilder_p.h>

**Comment by jmirabel** [comment]
> I added a print statement and it appears Qt5_Core_PRIVATE_INCLUDE_DIRS is empty.

I think (not sure though) it is `Qt5Core_PRIVATE_INCLUDE_DIRS` and not `Qt5_Core_PRIVATE_INCLUDE_DIRS`.

**Comment by updega2** [comment]
Yes, it is Qt5Core_PRIVATE_INCLUDE_DIRS and thats what I added the print statement for. I accidentally called it Qt5_CORE in the comment.

I've searched around and it appears this may be a Qt issue. This is my own build of Qt in which I did an out of source build. Based on this discussion https://bugreports.qt.io/browse/QTBUG-37417, it sounds like Qt does not populate the PRIVATE_INCLUDES variable in an out of source build.

**Comment by jmirabel** [comment]
By the way, on Ubuntu 16.04, the missing header comes with package `qtbase5-private-dev`. You may need to install it.

I think the presence of the package can be checked in CMake with `FIND_PACKAGE(Qt5Core COMPONENTS Private)` but again I am not 100% sure.

**Comment by jmirabel** [comment]
> I've searched around and it appears this may be a Qt issue. This is my own build of Qt in which I did an out of source build. Based on this discussion https://bugreports.qt.io/browse/QTBUG-37417, it sounds like Qt does not populate the PRIVATE_INCLUDES variable in an out of source build.

Then my comment is likely not related.

**Comment by updega2** [comment]
@jmirabel @iltommi Thanks for the help.

Using a downloadable Qt5 distribution from Qt and pointing to that resolves the issue and everything builds fine. So, this seems to be a Qt bug with not setting PRIVATE_INCLUDES correctly in an out of source build.

**Comment by iltommi** [comment]
glad you fixed with official qt5. 
As reminder,I used qt 5.10.1 installed via brew and it worked as well
